'use strict';
const $ = id => document.getElementById(id);
let map, db, memories = [], markers = [], urls = [], pending = null, active = null, selected = false;
let toastTimer;
function notify(message) { $('status').textContent = message; clearTimeout(toastTimer); toastTimer = setTimeout(() => $('status').textContent = '', 6500); }
function openDB() { return new Promise((resolve, reject) => { const r = indexedDB.open('memory-map', 1); r.onupgradeneeded = () => r.result.createObjectStore('photos', {keyPath:'id'}); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
function transaction(mode, action) { return new Promise((resolve, reject) => { const tx = db.transaction('photos', mode); const request = action(tx.objectStore('photos')); tx.oncomplete = () => resolve(request.result); tx.onerror = () => reject(tx.error); tx.onabort = () => reject(tx.error); }); }
function position() { return new Promise((resolve, reject) => { if (!window.isSecureContext) return reject(new Error('HTTPSで開いてください。')); if (!navigator.geolocation) return reject(new Error('位置情報に対応していません。')); navigator.geolocation.getCurrentPosition(p => resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}), () => reject(new Error('位置情報を取得できませんでした。地図で場所を選んでください。')), {enableHighAccuracy:true,timeout:12000,maximumAge:0}); }); }
async function compress(file) { if (!file.type.startsWith('image/')) throw new Error('画像ファイルを選んでください。'); if (file.size > 40 * 1024 * 1024) throw new Error('40MB以下の写真を選んでください。'); const url = URL.createObjectURL(file); try { const img = new Image(); img.src = url; await img.decode(); const scale = Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)); const canvas = document.createElement('canvas'); canvas.width = Math.round(img.naturalWidth*scale); canvas.height = Math.round(img.naturalHeight*scale); const ctx = canvas.getContext('2d'); ctx.fillStyle = '#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.drawImage(img,0,0,canvas.width,canvas.height); return await new Promise((resolve,reject) => canvas.toBlob(b => b ? resolve(b) : reject(new Error('写真を変換できませんでした。')), 'image/jpeg', .84)); } finally { URL.revokeObjectURL(url); } }
function date(value) { return new Date(value).toLocaleString('ja-JP', {year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}); }
function render() { markers.forEach(m => m.remove()); markers = []; urls.forEach(u => URL.revokeObjectURL(u)); urls = []; $('list').replaceChildren(); $('count').textContent = memories.length + ' 枚'; if (!memories.length) { const p = document.createElement('p'); p.className='empty'; p.textContent='まだ写真がありません。最初の一枚を撮ってみましょう。'; $('list').append(p); }
 memories.sort((a,b)=>b.createdAt-a.createdAt).forEach(photo => { const url = URL.createObjectURL(photo.blob); urls.push(url); const pin = document.createElement('div'); pin.className='photo-pin'; const image = document.createElement('img'); image.src=url; image.alt=photo.caption || '思い出の写真'; pin.append(image); const marker = L.marker([photo.lat,photo.lng], {icon:L.divIcon({html:pin,className:'',iconSize:[62,62],iconAnchor:[31,70]}),title:photo.caption || '写真を開く'}).addTo(map).on('click',()=>show(photo)); markers.push(marker); const card=document.createElement('button'); card.className='memory'; const thumb=image.cloneNode(); thumb.loading='lazy'; const text=document.createElement('span'); text.textContent=photo.caption || '名前のない思い出'; const time=document.createElement('small'); time.textContent=date(photo.createdAt); text.append(time); card.append(thumb,text); card.onclick=()=>{map.setView([photo.lat,photo.lng],16);show(photo);}; $('list').append(card); }); }
let detailURL, previewURL;
function show(photo) { active=photo; if(detailURL) URL.revokeObjectURL(detailURL); detailURL=URL.createObjectURL(photo.blob); $('detail-image').src=detailURL; $('detail-image').alt=photo.caption || '思い出の写真'; $('detail-title').textContent=photo.caption || '名前のない思い出'; $('detail-date').textContent=date(photo.createdAt); $('detail').showModal(); }
function updateLocation() { $('location-label').textContent = pending && Number.isFinite(pending.lat) ? '保存場所：' + pending.lat.toFixed(5) + ', ' + pending.lng.toFixed(5) + (pending.accuracy ? '（精度 約'+Math.round(pending.accuracy)+'m）' : '') : '保存する場所を地図で選んでください。'; $('save').disabled = !pending || !Number.isFinite(pending.lat); }
function selectPlace() { selected=true; $('editor').close(); $('place-hint').hidden=false; notify('地図をタップして場所を指定してください。'); }
function clearPending() { pending=null; selected=false; $('place-hint').hidden=true; if(previewURL) URL.revokeObjectURL(previewURL); previewURL=null; $('preview').removeAttribute('src'); $('file').value=''; $('capture').disabled=false; }
$('capture').onclick=()=>{if(pending) { $('editor').showModal(); return; } $('file').click();};
$('file').onchange=async()=>{const file=$('file').files[0]; if(!file)return; $('capture').disabled=true; notify('写真と現在地を準備しています…'); const placePromise=position().catch(()=>null); try { const blob=await compress(file); pending={id:crypto.randomUUID(),blob,createdAt:Date.now(),caption:''}; previewURL=URL.createObjectURL(blob); $('preview').src=previewURL; $('caption').value=''; const place=await placePromise; if(place) {Object.assign(pending,place);map.setView([place.lat,place.lng],16);} updateLocation(); $('editor').showModal(); notify(place ? '場所を確認して保存してください。' : '位置情報を取得できませんでした。「地図で場所を選び直す」を押してください。'); } catch(e) {clearPending();notify(e.message || '写真を読み込めませんでした。JPEGまたはPNGをお試しください。');} finally {$('capture').disabled=false;} };
$('choose').onclick=selectPlace;
$('cancel').onclick=()=>{$('editor').close();clearPending();};
$('editor').addEventListener('cancel',clearPending);
$('save-form').onsubmit=async event=>{event.preventDefault();if(!pending || !Number.isFinite(pending.lat))return; $('save').disabled=true; try {pending.caption=$('caption').value.trim();await transaction('readwrite',s=>s.put(pending));memories.push(pending);render();$('editor').close();clearPending();notify('思い出を地図に保存しました。');}catch(e){notify('保存できませんでした。端末の空き容量やブラウザの保存設定を確認してください。');updateLocation();}};
$('close-detail').onclick=()=>$('detail').close();
$('delete').onclick=async()=>{if(!active || !confirm('この写真をこのブラウザから削除しますか？'))return;try {await transaction('readwrite',s=>s.delete(active.id));memories=memories.filter(p=>p.id!==active.id);$('detail').close();active=null;render();notify('写真を削除しました。');}catch(e){notify('削除に失敗しました。もう一度お試しください。');}};
function download(blob,name) {const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('download').onclick=()=>{if(active)download(active.blob,'memory-'+active.id+'.jpg');};
$('backup').onclick=async()=>{if(!memories.length)return notify('保存した写真がありません。');$('backup').disabled=true;try{const photos=await Promise.all(memories.map(p=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const {blob,...meta}=p;resolve({...meta,image:r.result});};r.onerror=reject;r.readAsDataURL(p.blob);})));download(new Blob([JSON.stringify({version:1,photos})],{type:'application/json'}),'memory-map-backup.json');notify('写真と撮影場所をJSON形式で書き出しました。');}catch(e){notify('書き出しに失敗しました。写真を個別にダウンロードしてください。');}finally{$('backup').disabled=false;}};
$('locate').onclick=async()=>{$('locate').disabled=true;try{const p=await position();map.setView([p.lat,p.lng],16);notify('現在地を表示しました。');}catch(e){notify(e.message);}finally{$('locate').disabled=false;}};
$('fit').onclick=()=>{if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds().pad(.2),{maxZoom:16});else notify('写真を保存すると地図上に表示されます。');};
async function init() {try{if(!window.L)throw new Error('地図を読み込めませんでした。通信状態を確認して再読み込みしてください。');map=L.map('map',{zoomControl:true}).setView([31.5966,130.5571],12);const tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);let warned=false;tiles.on('tileerror',()=>{if(!warned){notify('一部の地図を読み込めません。ネットワーク接続を確認してください。');warned=true;}});map.on('click',e=>{if(!selected||!pending)return;pending.lat=e.latlng.lat;pending.lng=e.latlng.lng;delete pending.accuracy;selected=false;$('place-hint').hidden=true;updateLocation();$('editor').showModal();});db=await openDB();memories=await transaction('readonly',s=>s.getAll());render();if(markers.length)$('fit').click();new ResizeObserver(()=>map.invalidateSize()).observe($('map'));}catch(e){notify(e.message || '初期化に失敗しました。');['capture','locate','fit','backup'].forEach(id=>$(id).disabled=true);}}
init();
